project:
  type: book

book:
  title: "Enhancing Research Reproducibility and Collaboration with RStudio, Git, and GitHub"
  author: "JP Courneya"
  date: "`r Sys.Date()`"
  chapters:
    - index.qmd
    - RBasics.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

